name: Step 6

on:
  workflow_call:
    inputs:
      exercise-title:
        required: true
        type: string
      intro-message:
        required: true
        type: string

jobs:
  start_exercise:
    name: "My first action in the github worflow"
    uses: MexaGit/skills-hello-github-actions/.github/workflows/6-step.yml@main
    with:
      excecise-title: "Github Actions"
      intro-message: "Hi all"
    
